### PR TITLE
Add UUID library to build xrdpfc_print

### PR DESCRIPTION
**Pull request by djw8605**
This was required in order to build master just now.

### CODE REVIEW

**Comment by osschar** [comment]
@djw8605 @simonmichal why is this needed? Apparently it is pulled in through libXrdCl.

libXrdPfc is also linked against libXrdCl and not libuuid.

And so is xrdfs.

**Comment by abh3** [comment]
Correct, these two pull requests failed to apply due to new depdnencies 
that were not fully resolved. So, we are not applyingthem until we can 
figure out why these were submitted?

Andy

**Comment by abh3** [comment]
Could provide a reason of why this dependency is needed when we never needed it before?

**Comment by simonmichal** [comment]
@djw8605 : on which platform is this needed? From what I see all our CI builds are green: 
https://gitlab.cern.ch/dss/xrootd/-/pipelines/2182085

**Comment by djw8605** [comment]
I think I may have caught master at just the wrong time?  The UUID requirement was needed when I was building on EL7 at commit 7c190900b679d4327cb74b043affa880a74a6e7d.  But I can't replicate the need for uuid when I build from the current master, so I'm closing this pull request as unreproducible.

**Pull request closed without merging**
