### PR TITLE
XrdHttp: allow to use StartSimpleResp and SendData without breaking ABI

### PR DESCRIPTION
**Pull request by apeters1971**
This is really sort of ugly, but there is no better way without breaking the ABI and if one cannot return data in portions, I cannot return files larger then few MB. I use two non existing HTTP codes to do this (0 = StartResponse 1=SendData) . If you have a better idea, let me know.

### CODE REVIEW

**Comment by bbockelm** [comment]
Do the clients not accept chunked responses, or do they not accept chunked responses where the size isn’t known?  Can you provide the correct Content-Length header and work around it?

What’s the CERNbox client based on ?

**Comment by ffurano** [comment]
I would modify StartChunkedResp so that it avoids adding unconditionally the header line
  ss << "Transfer-Encoding: chunked";

and then simply use it by passing a Content-Length header. IMO it should work, what do you think?

**Comment by apeters1971** [comment]
If you put content-length this includes also the chunked encoding tags \r\n\ + size headers ... that does not work. If we remove Transfer-Encodign: chunked in StartChunkedResps, the sender function still encodes chunks, which breaks the specification.

**Comment by bbockelm** [comment]
Gotcha, thanks!

One last question - for future reference, what's the CERNbox client?  Seems strange that a HTTP client doesn't support chunked encoding.

**Comment by ffurano** [comment]
Well, I think that every other workaround we imagined is not less ugly than this one
The hope is to turn this into a proper addition to the API for Xrootd 5

**Pull request merged**
