### PR TITLE
Make Xrdhttp secure by default, by rejecting proxy cert in the absence of a proper SecXtractor plugin

### PR DESCRIPTION
**Pull request by ffurano**
Fix some minor memory leaks
Change the secxtractor interface to use the new lib and initialize it properly

### CODE REVIEW

**Comment by bbockelm** [comment]
A few issues with this one:
- Breaks backward compatibility with existing plugins.
- No versioning bump when breaking the backward compatibility.
- Now requires a client certificate for access, which is new behavior.  We currently allow unauthenticated clients to download, but allow additional authorization based on the ACC.
- Lots of strange whitespace.
- Changes in timeouts - can you add comments as to why?
- Lots of old code commented out.  Can probably just delete that and rely on git for history.

**Comment by ffurano** [comment]
Hi Brian,

 thanks for having a look.

On 12/20/2016 03:44 AM, Brian Bockelman wrote:
> A few issues with this one:
> 
>   * Breaks backward compatibility with existing plugins.

 indeed, we can add a  deprecation in the spec, when we decide how to release it.
 Or would you prefer a runtime check ?

>   * No versioning bump when breaking the backward compatibility.

 Uhm, I had increased the version number on the plugin. Which version number are you referring to ?

>   * Now requires a client certificate for access, which is new behavior. We currently allow unauthenticated clients to download,
>     but allow additional authorization based on the ACC.


 Do you mean unauthenticated but still through https ? Ok, should be the option SSL_VERIFY_FAIL_IF_NO_PEER_CERT,
I'll have a try.


>   * Lots of strange whitespace.
>   * Changes in timeouts - can you add comments as to why?

 It was one second, less than a roundtrip in some cases. Do you see any problem ? I did with one second.

>   * Lots of old code commented out. Can probably just delete that and rely on git for history.


 Ok!
 I'm doing these points except the versioning thing, we need one more exchange for that imo.

Fabrizio

**Comment by xrootd-dev** [comment]
Ok, I've submitted a little pull request containing:

 - now xrdhttp allows unauthenticated https clients
   (you also need to update xrdhttpvoms if you use it)
 - remove blank lines and comments

 About versioning we should decide what to do after the Christmas break. So far
the xrdhttpvoms was not released officially in any repo, but I agree that we should
prevent future version-based troubles.
 We should decide mainly how to release it (xrootd tree or alone in epel or wlcg)
and how to defend from version alchemies.

 Please let me know how it goes on your side.
 Fabrizio

**Comment by bbockelm** [comment]
For the versioning - I didn't see a version bump in this PR?  Did it go in earlier?

@abh3 will have to provide input here with regards to the best way to handle the version incompatibilities, but we need to generally keep ABI compatibility I believe.

**Comment by ffurano** [comment]
Now I see, you were referring to the xrootd version. I don't know what to say about that, so I'd leave it
to Andy/Michal. So far for me it's stuff into the master.

I agree with keeping the ABI compat for public interfaces. Not for private ones though. I'd like
to discuss how to release the voms extractor. In the absence of other decisions, I'll try
to release it to wlcg in January, after CERN reopens.

Fabrizio

**Pull request merged**
