### PR TITLE
XrdTls: XrdTlsTempCA - Refactored CASet and CRLSet to open the output file only once before the processing

### PR DESCRIPTION
**Pull request by ccaffy**
This PR is coming from the PR https://github.com/xrootd/xrootd/pull/2073.

The Maintenance thread creates bundle CA and CRL files. Before this modification, the output files created by the maintenance were open and closed for each CA and CRL read. It is not the case anymore. There is only one open at the beginning of the processing and one close at the end.

### CODE REVIEW

**Review by abh3 — COMMENTED** [review]
Well, this is rather an extensive charge *though for the better). I can inly assume it has been tested ad nauseum. So, if you confirm that is the case I will approve.

**Comment by ccaffy** [comment]
> Well, this is rather an extensive charge *though for the better). I can inly assume it has been tested ad nauseum. So, if you confirm that is the case I will approve.

It's just using RAII to open the file in the constructor and close it when the object is destroyed. I tested it and got no issue. Used `lsof -t` on the concatenated CRL and CA files, with no output --> everything looks good to me ;)

**Comment by abh3** [comment]
Thanks for confirming that :-)

**Review by abh3 — APPROVED** [review]
Can't see anything wrong here. This is a good improvement!

**Pull request merged**
