### PR TITLE
Adding ObjAdd to list of scitokens functions exported

### PR DESCRIPTION
**Pull request by djw8605**
- [x] Built
- [ ] Tested

(Still building)

### CODE REVIEW

**Comment by abh3** [comment]
Given that this causes problems, could you explain why this pull request was summited? I see no functional reason for it.

**Comment by simonmichal** [comment]
@djw8605 : could you please instead of merging the master branch into your devel branch, rebase it on master? Merging it as it is now to master would create havoc in history.

**Comment by djw8605** [comment]
Rebased to master.  

This pull request was requested by the latest testing errors that the OSG experienced.  The exact error was that it could not find the object `XrdAccAuthorizeObjAdd`, which I confirmed with `nm -D`.  The next error in the xrootd log was a failure to find version information for the `XrdAccAuthorizeObjAdd` function.

**Comment by simonmichal** [comment]
Thanks!

**Pull request merged**
