### PR TITLE
Fix a couple small issues caught by gcc 4.9.2

### PR DESCRIPTION
**Pull request by fritzm**
- Add missing #include <cstddef>
- Fix inadvertent sizeof pointer instead of sizeof pointee

### CODE REVIEW

**Comment by abh3** [comment]
Beat you to the fix. The repo already has these. However, I used the "old" stddef.h include instead of cstddef  to add a bit more backward compatibility. You could try what is in git head and if the old-style header is a problem we can substitute the new style header. Shall I close this pull?

**Comment by fritzm** [comment]
Oh, okay -- you have these changes on master, not the xrdssi branch then?

**Comment by abh3** [comment]
Uh, no, it's in the xrdssi branch in master.

**Comment by fritzm** [comment]
Surprised these diffs showed up in the pull request, ha!  Lemme pull the latest and give it a go...

**Comment by fritzm** [comment]
Looks good, thanks!  Closing PR as changes were already implemented upstream.

**Pull request closed without merging**
