### PR TITLE
[XrdCrypto][XrdHttp] Extract DN from user (proxy, multi-proxy) certif…

### PR DESCRIPTION
**Pull request by esindril**
…icate and properly

  handle the gridmap-file functionality when accessing through HTTP

This pull request is aimed at R5.

### CODE REVIEW

**Comment by esindril** [comment]
There is still the issue that if the certificate is not retrieved and we fail then no token (macaroon, scitoken etc) access is possible. For the moment this is allowed, therefore tokens work with the PR. This happens here:
https://github.com/xrootd/xrootd/pull/1238/files#diff-7b19b9632974132e3ff4f2f2f1924e1aR108

**Comment by esindril** [comment]
Hi Andy,

This is now ready from my side. Note this PR is done against the current master.

Thanks,
Elvin

**Comment by abh3** [comment]
Hi Elvin,

Thanks! I hear that this will need to be backported. Do you think you 
could hustle up a version for 4.12.x stable?

Andy

**Comment by esindril** [comment]
I am preparing that one now and this will be in #1239 done against the stable-4.12.x branch.

**Pull request merged**
