### PR TITLE
Return permission denied when overwrites are not allowed

### PR DESCRIPTION
**Pull request by bbockelm**
For the new "exclusive create" permission (meaning "never overwrite existing data"), if the file cannot be created due to the destination existing, we should return a "permission denied".

This also fixes a relatively serious issue in the built-in AuthDB module where it may incorrectly authorize the creation of files due to an uninitialized memory read.

Fixes: #1752

### CODE REVIEW

**Comment by bbockelm** [comment]
@simonmichal - this definitely needs to be in 5.5.0 (at least the patch that incorrectly give folks 'create' access).  However, for PRs, do you want me to target `stable-5.5.x` like I've done or do you want me to target `master` and then cherry-pick?

**Comment by simonmichal** [comment]
@bbockelm : thanks for letting me know, please do the PR against master, I will sync the stable branch after it gets merged

**Comment by simonmichal** [comment]
@bbockelm : could you please drop the changes to `docs/ReleaseNotes.txt`. I think this is just a left over after changing the target branch from stable to master, and it will give me a conflict when merging to stable. Thanks!

**Comment by simonmichal** [comment]
@bbockelm : sorry I overlooked it's overwritten by #1765, please disregard my previous comment

**Pull request closed without merging**
