### PR TITLE
Allow clients without certificates to downgrade to non-TLS connection

### LINKED ISSUE #2020: XrdCl without certificates gets fatal error when connecting to ztn enabled instance
While enabling **ztn** in our eosatlas instance, we realized some clients that didn't have any certificate configuration in place where not able to connect to the instance at all. According to comments in the code [1] and the documentation, it was my understanding that if ztn fails for whatever reason the other non-TLS required protocols would still be attempted - however this is not the case.

As an example we use the following configuration on the server side:
```
sec.protocol  ztn
sec.protbind  * only ztn krb5 gsi sss unix
```

This gives the following error on the client side, from a machine where the `/etc/grid-security/certificates/` directory is missing or even if it exists and it's empty:

``` XRD_LOGLEVEL=Dump XrdSecPROTOCOL=krb5 xrdfs roots://eosatlas-ns-ip700.cern.ch:2001/ stat /eos/
....
[2023-05-31 15:23:43.905613 +0200][Dump   ][Utility           ] Path:      
[2023-05-31 15:23:43.905651 +0200][Debug  ][PostMaster        ] Creating new channel to: roots://eosatlas-ns-ip700.cern.ch:2001/
[2023-05-31 15:23:43.905814 +0200][Debug  ][PostMaster        ] [eosatlas-ns-ip700.cern.ch:2001] Stream parameters: Network Stack: IPAuto, Connection Window: 120, ConnectionRetry: 5, Stream Error Window: 1800
[2023-05-31 15:23:43.905854 +0200][Debug  ][TaskMgr           ] Registering task: "TickGeneratorTask for: roots://eosatlas-ns-ip700.cern.ch:2001/" to be run at: [2023-05-31 15:23:58 +0200]
[2023-05-31 15:23:43.905873 +0200][Dump   ][PostMaster        ] [eosatlas-ns-ip700.cern.ch:2001] Sending message kXR_stat (path: /eos/, flags: none) (0x10714f0) through substream 0 expecting answer at 0
[2023-05-31 15:23:43.905943 +0200][Debug  ][PostMaster        ] [eosatlas-ns-ip700.cern.ch:2001] Found 1 address(es): [::ffff:128.142.52.31]:2001
[2023-05-31 15:23:43.906024 +0200][Debug  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Attempting connection to [::ffff:128.142.52.31]:2001
[2023-05-31 15:23:43.906099 +0200][Debug  ][Poller            ] Adding socket 0x1076440 to the poller
[2023-05-31 15:23:43.906407 +0200][Debug  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Async connection call returned
[2023-05-31 15:23:43.906479 +0200][Debug  ][XRootDTransport   ] [eosatlas-ns-ip700.cern.ch:2001.0] Sending out the initial hand shake + kXR_protocol
[2023-05-31 15:23:43.906525 +0200][Dump   ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Wrote a message:  (0x68000950), 44 bytes
[2023-05-31 15:23:44.094428 +0200][Dump   ][XRootDTransport   ] [msg: 0x68000ab0] Expecting 8 bytes of message body
[2023-05-31 15:23:44.094470 +0200][Dump   ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Received message header, size: 8
[2023-05-31 15:23:44.094490 +0200][Dump   ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Received a message of 16 bytes
[2023-05-31 15:23:44.094510 +0200][Debug  ][XRootDTransport   ] [eosatlas-ns-ip700.cern.ch:2001.0] Got the server hand shake response (type: manager [], protocol version 511)
[2023-05-31 15:23:44.094532 +0200][Dump   ][XRootDTransport   ] [msg: 0x68000ab0] Expecting 8 bytes of message body
[2023-05-31 15:23:44.094538 +0200][Dump   ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Received message header, size: 8
[2023-05-31 15:23:44.094547 +0200][Dump   ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Received a message of 16 bytes
[2023-05-31 15:23:44.094561 +0200][Debug  ][XRootDTransport   ] [eosatlas-ns-ip700.cern.ch:2001.0] kXR_protocol successful (type: manager [], protocol version 511)
[2023-05-31 15:23:44.094827 +0200][Debug  ][XRootDTransport   ] [eosatlas-ns-ip700.cern.ch:2001.0] Sending out kXR_login request, username: esindril, cgi: xrd.cc=ch&xrd.tz=1&xrd.appname=xrdfs&xrd.info=&xrd.hostname=elvin-dev01.cern.ch&xrd.rn=v5.5.5, dual-stack: true, private IPv4: 
false, private IPv6: false
[2023-05-31 15:23:44.094854 +0200][Debug  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] TLS hand-shake exchange.
[2023-05-31 15:23:44.104932 +0200][Debug  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] TLS hand-shake exchange.
[2023-05-31 15:23:44.105438 +0200][Error  ][TlsMsg            ] [] TLS error rc=-1 ec=1 (error_ssl) errno=0.
[2023-05-31 15:23:44.105486 +0200][Debug  ][TlsMsg            ] [] 140447345358592:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:
[2023-05-31 15:23:44.105507 +0200][Error  ][TlsMsg            ] Failed to do TLS connect: Unable to connect to eosatlas-ns-ip700.cern.ch; error_ssl
[2023-05-31 15:23:44.105526 +0200][Error  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Socket error while handshaking: [FATAL] TLS error: resource temporarily unavailable
[2023-05-31 15:23:44.105536 +0200][Debug  ][AsyncSock         ] [eosatlas-ns-ip700.cern.ch:2001.0] Closing the socket
[2023-05-31 15:23:44.105550 +0200][Debug  ][Poller            ] <[::ffff:137.138.124.135]:50036><--><[::ffff:128.142.52.31]:2001> Removing socket from the poller
[2023-05-31 15:23:44.105662 +0200][Error  ][PostMaster        ] [eosatlas-ns-ip700.cern.ch:2001] elapsed = 1, pConnectionWindow = 120 seconds.
[2023-05-31 15:23:44.105694 +0200][Error  ][PostMaster        ] [eosatlas-ns-ip700.cern.ch:2001] Unable to recover: [FATAL] TLS error: resource temporarily unavailable.
[2023-05-31 15:23:44.105710 +0200][Error  ][XRootD            ] [eosatlas-ns-ip700.cern.ch:2001] Impossible to send message kXR_stat (path: /eos/, flags: none). Trying to recover.
[2023-05-31 15:23:44.105722 +0200][Debug  ][XRootD            ] [eosatlas-ns-ip700.cern.ch:2001] Handling error while processing kXR_stat (path: /eos/, flags: none): [FATAL] TLS error: resource temporarily unavailable.
[2023-05-31 15:23:44.105740 +0200][Info   ][XRootD            ] [eosatlas-ns-ip700.cern.ch:2001] Retrying request: kXR_stat (path: /eos/, flags: none).
[2023-05-31 15:23:44.105779 +0200][Dump   ][Utility           ] URL: fake://fake:111//eos/
....
```

I guess this is an incorrectly implemented client behavior?! Assuming this can be easily fixed, is there anything that can be done server side for old clients that are already out?

Thanks!

[1] https://github.com/xrootd/xrootd/blob/master/src/XrdXrootd/XrdXrootdConfig.cc#L628

### PR DESCRIPTION
**Pull request by amadio**
Fixes #2020.

### CODE REVIEW

**Review by abh3 — COMMENTED** [review]
I don't see anything wrong here but I was somewhat confused of why --notls was introduced when --notlsok seems to pretty much do the same thing (OK, --notlsok is server oriented and --notls is client oriented). Can't we just expand --notlsok to include server non-support as well as client non-support? This does away with a somewhat confusing option. Additionally, why do we need a new option at all to solve this problem. If the client can't do TLS for any reason then it is deemed not TLS capable just like older clients. So, I am still puzzled at the introduction of the new option.

**Comment by amadio** [comment]
The end result is just a product of how I went about making it work the first time. I needed a way to tell the server right at the beginning that the client cannot do TLS, but maybe this final result can be refactored to not need a new option indeed. Let's discuss next week when you are around. Have a nice weekend and a safe trip!

**Comment by amadio** [comment]
I created a minimal patch to work around the issue, as suggested. The latest version has the following behavior:
```
$ # client has the required certificates to use TLS (no ztn token, so falls back to krb5)
$ xrdcp --force roots://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[4kB/4kB][100%][==================================================][4kB/s]  

$ # client has the CA directory, but it doesn't contain valid certificates (fails to validate server)
$ X509_CERT_DIR=/ xrdcp --force root://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: resource temporarily unavailable:  (source)

$ # CA certificate directory does not exist, is not readable, etc
$ X509_CERT_DIR=/dev/null xrdcp --force root://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: Failed to initialize TLS context (source)

$ # CA certificate directory does not exist, is not readable, etc (with --notlsok option)
$ X509_CERT_DIR=/dev/null xrdcp --force --notlsok root://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[4kB/4kB][100%][==================================================][4kB/s]  

$ # CA certificate directory does not exist, is not readable, etc (with --notlsok option, but roots:// instead of root://)
$ X509_CERT_DIR=/dev/null xrdcp --force --notlsok roots://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: Failed to initialize TLS context (source)

$ # client has the CA directory, but it doesn't contain valid certificates (with roots:// instead of root://)
$ X509_CERT_DIR=/ xrdcp --force roots://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: resource temporarily unavailable:  (source)

$ # client has the CA directory, but it doesn't contain valid certificates (with --notlsok option, but roots:// instead of root://)
$ X509_CERT_DIR=/ xrdcp --force --notlsok roots://eospilot.cern.ch//eos/pilot/opstest/amadio/4K.dat .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: resource temporarily unavailable:  (source)
```

**Comment by xrootd-dev** [comment]
Any change of making the message
TLS error: resource temporarily unavailable
  more specific towhtthe problem is or at least implying that this is a 
cert problem?

**Comment by amadio** [comment]
I though about that, but this is coming from the `errno` from [here](https://github.com/xrootd/xrootd/blob/master/src/XrdTls/XrdTlsSocket.cc#L291-L303), so I don't know a good/easy way to have a better message, but at least if you enable debug level for logging you will get messages like:

```
[2023-06-13 13:37:03.848977 +0200][Debug  ][AsyncSock         ] [eospilot.cern.ch:1094.0] Attempting connection to [::ffff:128.142.53.25]:1094
[2023-06-13 13:37:03.849007 +0200][Debug  ][Poller            ] Adding socket 0xf12e0b50 to the poller
[2023-06-13 13:37:03.849422 +0200][Debug  ][AsyncSock         ] [eospilot.cern.ch:1094.0] Async connection call returned
[2023-06-13 13:37:03.849438 +0200][Debug  ][XRootDTransport   ] [eospilot.cern.ch:1094.0] Sending out the initial hand shake + kXR_protocol
[2023-06-13 13:37:03.849450 +0200][Dump   ][AsyncSock         ] [eospilot.cern.ch:1094.0] Wrote a message:  (0x580015e0), 44 bytes
[2023-06-13 13:37:03.849923 +0200][Dump   ][XRootDTransport   ] [msg: 0x58001420] Expecting 8 bytes of message body
[2023-06-13 13:37:03.849933 +0200][Dump   ][AsyncSock         ] [eospilot.cern.ch:1094.0] Received message header, size: 8
[2023-06-13 13:37:03.849938 +0200][Dump   ][AsyncSock         ] [eospilot.cern.ch:1094.0] Received a message of 16 bytes
[2023-06-13 13:37:03.849941 +0200][Debug  ][XRootDTransport   ] [eospilot.cern.ch:1094.0] Got the server hand shake response (type: manager [], protocol version 511)
[2023-06-13 13:37:03.849949 +0200][Dump   ][XRootDTransport   ] [msg: 0x58001420] Expecting 8 bytes of message body
[2023-06-13 13:37:03.849953 +0200][Dump   ][AsyncSock         ] [eospilot.cern.ch:1094.0] Received message header, size: 8
[2023-06-13 13:37:03.849959 +0200][Dump   ][AsyncSock         ] [eospilot.cern.ch:1094.0] Received a message of 16 bytes
[2023-06-13 13:37:03.849964 +0200][Debug  ][XRootDTransport   ] [eospilot.cern.ch:1094.0] kXR_protocol successful (type: manager [], protocol version 511)
[2023-06-13 13:37:03.850645 +0200][Debug  ][XRootDTransport   ] [eospilot.cern.ch:1094.0] Sending out kXR_login request, username: amadio, cgi: xrd.cc=ch&xrd.tz=1&xrd.appname=xrdcp&xrd.info=&xrd.hostname=gentoo.cern.ch&xrd.rn=v5.5.5-385-g2b42eba41, dual-stack: true, private IPv4: false, private IPv6: false
[2023-06-13 13:37:03.850654 +0200][Debug  ][XRootDTransport   ] [eospilot.cern.ch:1094.0] Server requested encryption, enabling TLS
[2023-06-13 13:37:03.850658 +0200][Debug  ][AsyncSock         ] [eospilot.cern.ch:1094.0] TLS hand-shake exchange.
[2023-06-13 13:37:03.856412 +0200][Debug  ][AsyncSock         ] [eospilot.cern.ch:1094.0] TLS hand-shake exchange.
[2023-06-13 13:37:03.856518 +0200][Error  ][TlsMsg            ] [] error:00000001:lib(0):func(0):reason(1)
[2023-06-13 13:37:03.856527 +0200][Debug  ][TlsMsg            ] [] 139824434509504:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../openssl-1.1.1u/ssl/statem/statem_clnt.c:1919:
[2023-06-13 13:37:03.856532 +0200][Error  ][TlsMsg            ] Failed to do TLS connect: Unable to connect to eospilot.cern.ch; error_ssl
[2023-06-13 13:37:03.856536 +0200][Error  ][AsyncSock         ] [eospilot.cern.ch:1094.0] Socket error while handshaking: [FATAL] TLS error: resource temporarily unavailable
[2023-06-13 13:37:03.856541 +0200][Debug  ][AsyncSock         ] [eospilot.cern.ch:1094.0] Closing the socket
```

which indicate that there was a verification failure of the server.

**Comment by esindril** [comment]
Thanks @amadio ! Looks good for me. Using `--notlsok` and `roots` looks a bit split brain, but I guess this is a user issues.

**Comment by amadio** [comment]
Hi @esindril, yes, my memory is that when I was discussing this with @abh, the conclusion was that when a `roots://` URL is used, we should never allow falling back to non-encrypted connections for security reasons. However, if `root://` is used, `--notlsok` will work to not enforce promotion to use encryption.

**Comment by abh3** [comment]
That is correct. The expectation of roots/xroots/https protocols is that 
you *will* use TLS encryption. If you can't the connection should fail 
otherwise we are letting you run wha should have been encrypted over an 
unencrypted connection which from a security standpoint is really bad.

**Comment by amadio** [comment]
Ok, I'm merging this as is then. Thanks!

**Pull request merged**
