### PR TITLE
Pfc purge v2

### PR DESCRIPTION
**Pull request by osschar**
Purge algorithm can now also consider space used by cached files and age of files. The main purpose is to allow several xcache instances to share the same set of disks.

### CODE REVIEW

**Comment by bbockelm** [comment]
Aren't you worried by the fact that GCC seems to think that `GetSizeInBytes()` can be replaced by the constant `0`?  Is there something the compiler is seeing which we aren't?

**Comment by osschar** [comment]
No, not worried :) Found this:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61294
And then, the call to Info::GetSizeInBytes() (inline) can return 0 ... leading to optimizer producing a different path (and memset call) for == 0 case. And this brings up the warning that tells you you might have transposed the parameters (as people usually set memory to 0, not to 255 as we do here).

**Comment by bbockelm** [comment]
Ah, clever GCC.

Can you add a link to the GCC bug explaining why you don't use memset here?

(Alternately, is there an attribute we can set to suppress warnings?)

**Comment by osschar** [comment]
I could put something like:
`
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Werror"
  memset(xxx, 255, GetSizeInBytes());                       /* no diagnostic for this one */
#pragma GCC diagnostic pop
`
or add comment like:
`
   // The following should be: memset(m_store.m_buff_synced, 255, GetSizeInBytes());
   // but GCC produces an overzealous 'possible argument transpose warning' and
   // xrootd build uses warnings->errors escalation.
   // See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61294
`

**Comment by bbockelm** [comment]
I like both!  For the comment, also include the compiler version that hit the issue.  That way, we can also remove the workaround at a later date.

Brian

**Comment by simonmichal** [comment]
@osschar : commit 87d162be15e5f41ad23bc85fa6b86e7d9f64e058 broke the OSX build:
https://gitlab.cern.ch/dss/xrootd/-/jobs/2164942
(there's no _posix_fallocate_ on OSX platform)

Could you fix it?

**Comment by osschar** [comment]
Thanks for the heads up! I'm on to it now.

**Comment by osschar** [comment]
@simonmichal the fix is in #827, apparently mozilla and KDE had the same problem :)

**Pull request merged**
