### PR TITLE
WIP: Add Travis CI configuration

### PR DESCRIPTION
**Pull request by alexpearce**
Given the positive reaction in #502, here's a PR with a Travis CI configuration file.

This PR is WIP while I figure out how to get as much as possible building on Travis (different compilers, Python versions, platforms, …). So, lots of little tests commits, then I'll rebase once things look good.

### CODE REVIEW

**Comment by alexpearce** [comment]
Ah. This PR was far from complete 😅

**Comment by simonmichal** [comment]
Ah. My bad, I was thinking it's just a stub to remove the warring that builds fail ;-)

Ho do we fix it?

**Comment by alexpearce** [comment]
Right now, I'm [having trouble even building the package](https://travis-ci.org/xrootd/xrootd/jobs/222125844#L509), so this is the first thing to address.

Once that's done, I need to set up the builds on the multiple platforms and for the various Python versions XRootD supports. That step should be easier.

**Comment by ljanyst** [comment]
You either revert the merge or reset the head to a past commit and force push. The second option is probably cleaner.

**Comment by simonmichal** [comment]
Thanks for the tip :)

**Pull request merged**
