### PR TITLE
Remove old files

### PR DESCRIPTION
**Pull request by ellert**
Consider at some point to remove files from the source tree that are no longer used.

### CODE REVIEW

**Comment by abh3** [comment]
This is going to take some review to determine whether these deletions will impact our longer term plans. Normally, we leave "unused" parts because some people still depend on the, we have plans to reintegrate parts of them, provide templates for similar functionality, etc. Leaving the source versions in the repo is rather harmless even if somewhat ugly. What was the motivation for these deletions?

**Comment by ellert** [comment]
> What was the motivation for these deletions?

I tried to phrase this carefully when I said "Consider at some point to remove". That is, I was not expecting this to be immediately accepted. The motivation was mainly to clean up the source distribution to not include dead code that is no longer used.

**Comment by abh3** [comment]
That's OK, nothing wrong with eliminating dead code as it is ugly and can be confusing. It just means we need to review the pull request to extract the appropriate essence. I do appreciate that you provided a focus target which gives us an important starting point. So, I hope you don't mind that a review will ask for modifications of this pull request. I think this is worth pursuing to its conclusion.

**Comment by ellert** [comment]
Rebased because the "Remove unused parts of XrdOucCache" commit was no longer relevant after commit f853b74cd51578d09ee58bde02e67828113e82c3 that removed the same files.

**Comment by simonmichal** [comment]
Just removed XrdClient: 644354de13d87d59a388bcd35856c96dbd27d05a

**Comment by ellert** [comment]
> Just removed XrdClient: 644354de13d87d59a388bcd35856c96dbd27d05a

I have rebased again. The files changed count went down from 114 to 49.

The XrdCns would need some porting if it should be kept since it currently requires XrdClient that is now removed.

**Comment by simonmichal** [comment]
`XrdCns` has been already removed from our builds, but lets wait for @abh3 for the final verdict.

**Comment by abh3** [comment]
I think we no longer compile that and have no expectations of forward 
porting it (i.e. it's dead code).

Andy

**Comment by simonmichal** [comment]
@ellert : just to let you know, I have removed `XrdCns` (actually the code has been moved to xrootd/archive repo).

**Comment by ellert** [comment]
> @ellert : just to let you know, I have removed `XrdCns` (actually the code has been moved to xrootd/archive repo).

@simonmichal : You left the src/XrdCns.cmake file behind (and the out-commented include statement in src/CMakeLists.txt) 😀

**Comment by ellert** [comment]
I have rebased again. Now there are just 19 files left... (Down from 49.)

**Comment by simonmichal** [comment]
> @simonmichal : You left the src/XrdCns.cmake file behind (and the out-commented include statement in src/CMakeLists.txt) 😀

@ellert : thanks for pointing it out! I removed the left overs in: 9a0b4ecd93f9d7904f4ce616d3f5be04d3735d0d

**Comment by ellert** [comment]
And we are down to 15 files...

**Comment by simonmichal** [comment]
I've just removed the obsolete man pages: 256873ed32936a3abf8d84af0d52f71dd497dbb5

**Comment by ellert** [comment]
And then they were 11...

**Comment by simonmichal** [comment]
@ellert : together with @abh3, we just did a review and the verdict is we want to keep following files:

```
XrdSecgsiAuthzFunDN.cc
XrdXrootdGPFile.hh
XrdPfcAllowDecision.cc 
XrdFrmAdminReloc.cc
```

Please modify your PR and then we can merge it.

**Comment by ellert** [comment]
> Please modify your PR and then we can merge it.

I have modified the PR as requested.

**Pull request merged**
