### PR TITLE
[XrdSecsss] Fix possible buffer overrun when serialising creds. Closes #2143

### LINKED ISSUE #2143: xrootd server abort when copying with tokens
Hi folks,

We've got a user with a server crash after copying a file using tokens.  The first copy works but subsequent copies appear to hang.  Their server is EL8; here's their traceback:

```
Nov 21 14:16:18 dtn2201 systemd[1]: Started Process Core Dump (PID 13561/UID 0).
Nov 21 14:16:19 dtn2201 systemd-coredump[13562]: Process 13441 (xrootd) of user 985 dumped core.

Stack trace of thread 13449:
#0 0x00007f19c5e73acf raise (libc.so.6)
#1 0x00007f19c5e46ea5 abort (libc.so.6)
#2 0x00007f19c5eb4cc7 __libc_message (libc.so.6)
#3 0x00007f19c5ebbfcc malloc_printerr (libc.so.6)
#4 0x00007f19c5ebc876 unlink_chunk.isra.2 (libc.so.6)
#5 0x00007f19c5ebdefb _int_free (libc.so.6)
#6 0x00007f19c721a1f0 _ZN12XrdSecsssEnt6DeleteEv (libXrdUtils.so.3)
#7 0x00007f19c721ad2a _ZN11XrdSecsssID8RegisterEPKcPK12XrdSecEntitybb (libXrdUtils.so.3)
#8 0x00007f19beae7e9b _ZN9XrdPssSys4DiscER9XrdOucEnv (libXrdPss-5.so)
#9 0x00007f19c74dc94d _ZN6XrdOfs4DiscEPK12XrdSecEntity (libXrdServer.so.3)
#10 0x00007f19c74c2749 _ZN17XrdXrootdProtocol7CleanupEv (libXrdServer.so.3)
#11 0x00007f19c74c3212 _ZN17XrdXrootdProtocol7RecycleEP7XrdLinkiPKc (libXrdServer.so.3)
#12 0x00007f19c7209224 _ZN10XrdLinkXeq5CloseEb (libXrdUtils.so.3)
#13 0x00007f19c7205e52 _ZN7XrdLink11setProtocolEP11XrdProtocolbb (libXrdUtils.so.3)
#14 0x00007f19c720c7c7 _ZN12XrdScheduler3RunEv (libXrdUtils.so.3)
#15 0x00007f19c720c8e9 _Z15XrdStartWorkingPv (libXrdUtils.so.3)
#16 0x00007f19c719b1a7 XrdSysThread_Xeq (libXrdUtils.so.3)
#17 0x00007f19c61f21ca start_thread (libpthread.so.0)
#18 0x00007f19c5e5ee73 __clone (libc.so.6)

...

Nov 21 14:16:19 dtn2201 systemd[1]: xrootd@dtn-eic.service: Main process exited, code=killed, status=6/ABRT
Nov 21 14:16:19 dtn2201 systemd[1]: xrootd@dtn-eic.service: Failed with result 'signal'.
```
For brevity, I omitted the tracebacks of the 16 other threads that looked fine, but I have the full traceback at https://pages.cs.wisc.edu/~matyas/debug/xrootd-5.6.3/fd74297-full-traceback.txt

The cconfig output for the xrootd executable for the instance (with hostname redacted) is:
```
all.export / 
ofs.osslib libXrdPss.so 
ofs.ckslib * libXrdPss.so 
pss.origin roots://XXXXXXXXX:1094 
pss.persona client strict verify 
xrootd.tls all 
xrd.tls /etc/grid-security/xrd/hostcert.pem /etc/grid-security/xrd/hostkey.pem 
xrd.tlsca certdir /etc/grid-security/certificates 
xrootd.seclib default 
ofs.authorize 
acc.authdb /etc/xrootd/Authfile 
acc.authrefresh 60 
ofs.authlib libXrdAccSciTokens.so 
sec.protocol ztn 
all.adminpath /var/spool/xrootd 
all.pidpath /var/run/xrootd 
sec.trace debug 
ofs.trace all 
xrootd.trace all 
scitokens.trace all debug 
ztn.trace all debug 
auth.trace all debug 
pss.trace all debug 
```

and the xrootd and scitokens RPMs:
```
scitokens-cpp-1.1.0-1.el8.x86_64
xrootd-client-5.6.3-1.3.osg23.el8.x86_64
xrootd-client-libs-5.6.3-1.3.osg23.el8.x86_64
xrootd-libs-5.6.3-1.3.osg23.el8.x86_64
xrootd-multiuser-2.1.3-1.3.osg36.el8.x86_64
xrootd-scitokens-5.6.3-1.3.osg23.el8.x86_64
xrootd-server-5.6.3-1.3.osg23.el8.x86_64
xrootd-server-libs-5.6.3-1.3.osg23.el8.x86_64
```

note that the xrootd RPMs are the 5.6.3-1 builds patched by OSG.  We have the following PRs applied as patches:
- https://github.com/xrootd/xrootd/pull/1868
- https://github.com/xrootd/xrootd/pull/2118

Any ideas?
Thanks,
-Mat

### PR DESCRIPTION
**Pull request by smithdh**
Fixes: #2143.

### CODE REVIEW

**Review by abh3 — APPROVED** [review]
I take it that the indecision between the value being 3 vs 4 has been resolved and 3 is actually the correct value.

**Comment by smithdh** [comment]
Hi Andy. The creds are packed with XrdOucPup::Pack(p,data,len), for a char* data of length len, where Pack needs 2+len bytes. We add another +1 byte for the type tag. (Hence len+3). But in many places we serialise strings with XrdOucPup::Pack(p,str) where Pack needs 2+strlen(str)+1 for the Pack, and +1 byte for the type tag. (Hence strlen(str)+4). So that's where the 3 vs 4 comes from. The creds are the first case and I verified also at packing time that this length is right.

There is another (optional) field where we are overcounting by 1 byte (hence allocating 1 byte more than is strictly needed for the serialisation buffer, if the optional field is included), but for simplicity I didn't adjust that in this patch.

**Comment by amadio** [comment]
Thanks @smithdh for the details. I'm merging this then.

**Comment by abh3** [comment]
Hi David,

That's what I expected from our last discussion about this. Thank you for the in-depth analysis!

Andy
________________________________

**Pull request merged**
