### PR TITLE
[XrdCl] Avoid partially reading status message data too early

### PR DESCRIPTION
**Pull request by smithdh**

### CODE REVIEW

**Comment by abh3** [comment]
I will leave it to Michal to approve though he won't be back in action until Monday. However, it you could provide what the erroneous result is that would be helpful (i.e. what kind of error results).

**Comment by smithdh** [comment]
I've added an issue to describe the original problem, what was seen etc. Issue #1420. Thanks.

**Comment by abh3** [comment]
Hi David,

Superlative analysis, as always. Thanks!

Andy

**Comment by simonmichal** [comment]
@smithdh : good catch, thanks a lot!

**Pull request merged**
