### PR TITLE
Append signed Diffie-Hellman paramaters to the unsigned

### PR DESCRIPTION
**Pull request by wyang007**
The server appends signed Diffie-Hellman parameters to the unsigned so that the client can verify. If the verification fails, x509 proxy delegation will be turned off. This change is backward compatible to the older clients.

### CODE REVIEW

**Comment by abh3** [comment]
Could you un-comment the message

std::cerr <<"secgsi: proxy delegation forbidden when server does not provide signed DH parameter!\n"

that indicates delegation was turned off. Without that message we will be chasing delegation problems for days. With the message we will immediately know why i didn't work. A small price to pay for a message.

**Comment by abh3** [comment]
Ah, are you telling me this is a server-side issue? That is, the message 
only appears at the server? If so, I think this is a bit more complicated 
then. If it's a client-side issue then the check with turnoff is correct.

On Wed, 5 Dec 2018, Wei Yang wrote:

> I put it there and comment it out because I feel the message is quite 
misleading: In a TPC case, if the source does not send DH parameters (but 
the destination does), this message will come out, even though the client 
never intended to delegate the proxy to the source.

**Comment by wyang007** [comment]
It is at the client side. XrdSecProtocolgsi::ClientDoCert() is called by client only.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by xrootd-dev** [comment]
OK, then do what I did when checking if DNS was used and if delegation is 
enabled, urn it off with a message. Otherwise, stay silent.

**Comment by wyang007** [comment]
Andy, I switch to use x2b and b2x, and test it. Please review and merge.

**Comment by wyang007** [comment]
replaced by PR #869

**Pull request closed without merging**
