### PR TITLE
[CMake] Make switches for server-only options dependent on XRCL_ONLY=FALSE

### PR DESCRIPTION
**Pull request by amadio**
Fixes: ff67c2a0, Closes: #1804

### CODE REVIEW

**Comment by amadio** [comment]
@simonmichal I guess at least `ENABLE_VOMS` could be turned into a dependent option as well. Which other options are client-only?

**Comment by simonmichal** [comment]
@amadio : thanks a lot for the PR :-)

I think, it is worth investigating first why did we run into the problem described in #1804 in the first place, if I read the code correctly, if the `XRDCL_ONLY` is set to true Macaroons and SciTokens plug-ins should have been excluded from the build:
https://github.com/xrootd/xrootd/blob/6ef78195d2279a2e462f2aaae831859822e2a6f9/src/CMakeLists.txt#L52-L88

or do I miss something?

**Comment by amadio** [comment]
The lookup for SciTokens and Macaroons happens in [cmake/XRootDFindLibs.cmake](https://github.com/xrootd/xrootd/blob/master/cmake/XRootDFindLibs.cmake#L122-L157) and that's not protected with `if(NOT XRDCL_ONLY)`. That's why I said maybe moving the calls to `find_package(...)` into the subdirectories where they are needed could make sense. It's an alternative solution to what I'm proposing here, but may not be as nice if multiple subdirectories depend on the same packages, as those would be needed at top level anyway.

**Review by simonmichal — APPROVED** [review]

**Comment by simonmichal** [comment]
@amadio : thanks for the explanation, it all makes sense now!

**Pull request merged**
