### PR TITLE
Stable release 5.5.2, release candidate 2

### PR DESCRIPTION
**Pull request by amadio**
These are cherry-picks from `master` into `stable-5.5.x`. Please ack before I create the new tag tomorrow.

### CODE REVIEW

**Comment by xrootd-dev** [comment]
Hi Guilherme,

Hmmm, odd -- lots of these are under the heading "feature" and should be 
put into a patch release. How did they get cherry picked?

Feature release stuff is marked with a '--'.

We should talk about the "update notes" ccommits. Never liked those and 
maybe we can think about how to handle them better.

Andy

On Thu, 15 Dec 2022, Guilherme Amadio wrote:

> These are cherry-picks from `master` into `stable-5.5.x`. Please ack before I create the new tag tomorrow.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/xrootd/xrootd/pull/1867
>
> -- Commit Summary --
>
>  * [Docs] Sync release notes.
>  * [Docs] Sync release notes.
-->* Update notes on crmode directive.
-->* Update notes on Mkdir return code change
-->* Update release notes on new gsi option.
>  * Update notes on formatting fix.
>  * Update notes on xrdcp cleanup.
***This entry seems like it's a merge of two entries.
>  * Update notes on patch for missing delete.Update notes on patch for missing delete.
-->* [PSS] Allow origin to be a directory of a locally mounted file system.
-->* Update notes on new Pss/Pfc feature.

**Review by abh3 — CHANGES_REQUESTED** [review]
As noted in the comments, some feature patches have sneaked into the patch release. This will be handled offline.

**Comment by amadio** [comment]
@abh, agreed, let's discuss this in the meeting. I cleaned up the commits a bit, and left the commits for release notes out. Once we agree on what goes in, I will handle the notes separately to make sure everything is properly documented.

**Comment by abh3** [comment]
Yep, good enough! See you at my 10 AM and your 7 PM.

**Pull request merged**
