### PR TITLE
Implement RFC 3230 digests for GET requests.

### PR DESCRIPTION
**Pull request by bbockelm**

### CODE REVIEW

**Comment by ffurano** [comment]
Hi Brian,
it went through the usual heavy tests and did not break anything else. Also the code looks very clean to me.

However it does not work well, and I am not sure it's due to your code.
In practice, every time I ask for a new checksum, it hangs. If I ask for a checksum that was already precalculated (e.g. a second time for the same checksum) instead it works fine.
The last line of this snippet is very suspicious to me, and is absent when the interaction works.

Here is a relevant log, showing what happens until it hangs:
190207 14:10:15 13886 sysXrdHttp:  Parsing first line: GET /dynafeds_demo/h1big.root?xrdhttptk=lg+XFygVr6bITWD9K9lX2A==&xrdhttptime=1549545015&xrdhttpname=%2FDC=ch%2FDC=cern%2FOU=Organic%20Units%2FOU=Users%2FCN=furano%2FCN=644746%2FCN=Fabrizio%20Furano&xrdhttpvorg
=dteam&xrdhttphost=%5B%3A%3Affff%3A188.184.31.59%5D&xrdhttpdn=%2FDC=ch%2FDC=cern%2FOU=Organic%20Units%2FOU=Users%2FCN=furano%2FCN=644746%2FCN=Fabrizio%20Furano%2FCN=190442999&xrdhttprole=NULL&xrdhttpgrps=%2Fdteam%20%2Fdteam%2FRole=NULL%20%2Fdteam%2FRole=NULL%2FCap
ability=NULL&xrdhttpendorsements=%2Fdteam%2FRole=NULL%2FCapability=NULL HTTP/1.1

190207 14:10:15 13886 sysXrdHttp:  rc:40 got hdr line: User-Agent: libdavix/0.7.1 neon/0.0.29

190207 14:10:15 13886 sysXrdHttp:  rc:14 got hdr line: Keep-Alive: 

190207 14:10:15 13886 sysXrdHttp:  rc:24 got hdr line: Connection: Keep-Alive

190207 14:10:15 13886 sysXrdHttp:  rc:14 got hdr line: TE: trailers

190207 14:10:15 13886 sysXrdHttp:  rc:36 got hdr line: Host: [::ffff:128.142.135.19]:1094

190207 14:10:15 13886 sysXrdHttp:  rc:22 got hdr line: Want-Digest: adler32

190207 14:10:15 13886 sysXrdHttp:  rc:2 got hdr line: 

190207 14:10:15 13886 sysXrdHttp:  rc:2 detected header end.
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting vorg: dteam
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting vorg: dteam
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting name: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting name: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting host: [::ffff:188.184.31.59]
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting host: [::ffff:188.184.31.59]
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting dn: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano/CN=190442999
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting dn: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano/CN=190442999
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting role: NULL
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting role: NULL
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting grps: /dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting grps: /dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting endorsements: /dteam/Role=NULL/Capability=NULL
190207 14:10:15 13886 ?:7@lxplus115 sysXrdHttp:  Setting endorsements: /dteam/Role=NULL/Capability=NULL
190207 14:10:15 13886 XrootdMonitor: 340 bytes sent to xrootd.t2.ucsd.edu:9960 rc=0
190207 14:10:15 13886 XrootdBridge: /DC=ch/D.81:7@lxplus115 login as /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp:  Process. lp:0x7f0294001c78 reqstate: 0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdProtocol: 0000 Bridge req=3017 dlen=471 blen=471
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: Process is exiting rc:0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 ofs_stat:  fn=/dynafeds_demo/h1big.root
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdProtocol: 0000 rc=0 stat /dynafeds_demo/h1big.root
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdResponse: 0000 sending 41 data bytes
190207 14:10:15 13886 sysXrdHttp:  XrdHttpReq::Data! final=0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: PostProcessHTTPReq req: 2 reqstate: 0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: Stat for GET /dynafeds_demo/h1big.root stat=1672765207805185 280408881 49 1402658912
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp:  Process. lp:0 reqstate: 0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdProtocol: 0000 Bridge req=3001 dlen=488 blen=488
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: Process is exiting rc:0
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 ofs_chksum: adler32 fn=/dynafeds_demo/h1big.root
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdResponse: 0000 sending 18 data bytes; status=4006
190207 14:10:15 13886 /DC=ch/D.81:7@lxplus115 XrootdProtocol: 0000 Bridge waiting for resp; sid=0 wt=600 (Job scheduled.)
190207 14:10:15 13886 XrdSched: running chksum inq=0
190207 14:10:15 13886 http ofs_chksum: adler32 fn=/dynafeds_demo/h1big.root
190207 14:10:15 13956 XrdSched: running main accept inq=0
190207 14:10:16 13886 /DC=ch/D.81:7@lxplus115 XrdLink: Setting ref to 1+1 post=0
190207 14:10:16 13886 sysXrdHttp:  XrdHttpReq::Data! final=1
190207 14:10:16 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: PostProcessHTTPReq req: 2 reqstate: 1
190207 14:10:16 13886 /DC=ch/D.81:7@lxplus115 sysXrdHttp: Checksum for HEAD /dynafeds_demo/h1big.root adler32=76d98e99
190207 14:10:16 13886 XrdPoll: Poller 0 enabled /DC=ch/D.81:7@lxplus115
190207 14:10:16 13886 /DC=ch/D.81:7@lxplus115 XrdLink: Setting ref to 2+-1 post=0
190207 14:10:16 13886 XrootdsendResult: sent async ok to /DC=ch/D.81:7@lxplus115
[FF ^this is the suspicious line.]
[FF: and then ... nothing happens anymore]

**Comment by ffurano** [comment]
@abh3 ... Andy, does the line

190207 14:10:16 13886 XrootdsendResult: sent async ok to /DC=ch/D.81:7@lxplus115

of the previous log tell anything to you? IMO it should not go that way.

**Comment by xrootd-dev** [comment]
Hi Fabrizio,

Well, yes, checksum in XRootD are async in nature necause they may take a long time to execute. I don’t think there is anything in HTTP/1 protocol that can do async anything. So, it would seem that this little bit causes things to break. You may want to hold off on the merge as this will take some amount of thought to figure out how to do correctly. BTW, why do you use the first 8 characters of the cert for the login name? There are better ways of identifying the client.

Andy

**Comment by ffurano** [comment]
Hi Brian,

 well, I agree that they are async, yet if the request came from XrdBridge then
also the response has to come through XrdBridge. I consider this a bug of
the core.

 I'd like to have Andy's opinion on this.

 About the login name... that's history. I remember I needed just to fill that
field with something that is somehow human readable. What would you put there? Some
CN number?

f

**Comment by ffurano** [comment]
Oops, I mistakenly thought it was Brian answering... instead it was Andy :-P

**Comment by bbockelm** [comment]
Right - my understanding of the bug is that if the checksum must be computed, then the core NEVER responds over the protocol bridge.  I have no problem in waiting for a response, as everything else here is async.

Is that summary correct?

**Comment by ffurano** [comment]
Yes, sounds correct to me.

**Comment by abh3** [comment]
Hi Fabrizio,

I agree that since HTTP has no callback mechanism, waitresps whould be 
handled internally. They are already handled in the wait case. So, let me 
look as to what I can do here.

Andy

**Comment by xrootd-dev** [comment]
OK, I looked at the code and technically it is doing the right thing and 
handling kXR_waitresp in the expected way. Why the http thread is not 
resuming is mysterious as it should be. Anyway of running a checksum calc 
with full debugging turned on so we can see if here is something special 
going on in the checksum code path when the checksum has to be calculated?

Should that not provide sufficient info, is there a setup I can get to for 
a gdb session?

Andy

**Comment by ffurano** [comment]
Hi Andy,
 here's a log of a single request, made using "xrootd -d ..."

 The command to trigger the issue is (with a valid dteam proxy behind):

 $ davix-get -P grid -H "Want-Digest: md5" https://littlexrdhttp.cern.ch:1094/dynafeds_demo/ape.jpg /dev/null --trace header

 If you need I can give you access to my vanilla setup "littlexrdhttp". 

-----------------------------------------------------------------------------------------------------------------------------
190211 10:07:13 13902 sysXrdHttp:  Parsing first line: GET /dynafeds_demo/ape.jpg?xrdhttptk=rrVM1VvkuZhJLifgh2geKg==&xrdhttptime=1549876033&xrdhttpname=%2FDC=ch%2FDC=cern%2FOU=Organic%20Uni
ts%2FOU=Users%2FCN=furano%2FCN=644746%2FCN=Fabrizio%20Furano&xrdhttpvorg=dteam&xrdhttphost=%5B%3A%3Affff%3A188.184.31.59%5D&xrdhttpdn=%2FDC=ch%2FDC=cern%2FOU=Organic%20Units%2FOU=Users%2FCN=furano%2FCN=644746%2FCN=Fabrizio%20Furano%2FCN=786122054&xrdhttprole=NULL&xrdhttpgrps=%2Fdteam%20%2Fdteam%2FRole=NULL%20%2Fdteam%2FRole=NULL%2FCapability=NULL&xrdhttpendorsements=%2Fdteam%2FRole=NULL%2FCapability=NULL HTTP/1.1

190211 10:07:13 13902 sysXrdHttp:  rc:40 got hdr line: User-Agent: libdavix/0.7.1 neon/0.0.29

190211 10:07:13 13902 sysXrdHttp:  rc:14 got hdr line: Keep-Alive: 

190211 10:07:13 13902 sysXrdHttp:  rc:24 got hdr line: Connection: Keep-Alive

190211 10:07:13 13902 sysXrdHttp:  rc:14 got hdr line: TE: trailers

190211 10:07:13 13902 sysXrdHttp:  rc:36 got hdr line: Host: [::ffff:128.142.135.19]:1094

190211 10:07:13 13902 sysXrdHttp:  rc:18 got hdr line: Want-Digest: md5

190211 10:07:13 13902 sysXrdHttp:  rc:2 got hdr line: 

190211 10:07:13 13902 sysXrdHttp:  rc:2 detected header end.
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting vorg: dteam
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting vorg: dteam
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting name: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting name: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting host: [::ffff:188.184.31.59]
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting host: [::ffff:188.184.31.59]
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting dn: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano/CN=786122054
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting dn: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano/CN=786122054
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting role: NULL
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting role: NULL
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting grps: /dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting grps: /dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting endorsements: /dteam/Role=NULL/Capability=NULL
190211 10:07:13 13902 ?:7@lxplus115 sysXrdHttp:  Setting endorsements: /dteam/Role=NULL/Capability=NULL
190211 10:07:13 13902 XrootdMonitor: 343 bytes sent to xrootd.t2.ucsd.edu:9960 rc=0
190211 10:07:13 13902 XrootdBridge: /DC=ch/D.16468:7@lxplus115 login as /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp:  Process. lp:0x7f0294001c78 reqstate: 0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdProtocol: 0000 Bridge req=3017 dlen=468 blen=468
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: Process is exiting rc:0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 ofs_stat:  fn=/dynafeds_demo/ape.jpg
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdProtocol: 0000 rc=0 stat /dynafeds_demo/ape.jpg
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdResponse: 0000 sending 35 data bytes
190211 10:07:13 13902 sysXrdHttp:  XrdHttpReq::Data! final=0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: PostProcessHTTPReq req: 2 reqstate: 0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: Stat for GET /dynafeds_demo/ape.jpg stat=669744315301121 9943 49 1396526518
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp:  Process. lp:0 reqstate: 0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdProtocol: 0000 Bridge req=3001 dlen=481 blen=481
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: Process is exiting rc:0
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 ofs_chksum: md5 fn=/dynafeds_demo/ape.jpg
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdResponse: 0000 sending 18 data bytes; status=4006
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrootdProtocol: 0000 Bridge waiting for resp; sid=0 wt=600 (Job scheduled.)
190211 10:07:13 13902 XrdSched: running chksum inq=0
190211 10:07:13 13902 http ofs_chksum: md5 fn=/dynafeds_demo/ape.jpg
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrdLink: Setting ref to 1+1 post=0
190211 10:07:13 13902 sysXrdHttp:  XrdHttpReq::Data! final=1
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: PostProcessHTTPReq req: 2 reqstate: 1
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 sysXrdHttp: Checksum for HEAD /dynafeds_demo/ape.jpg md5=a6c819209001be98139faecf177d352c
190211 10:07:13 13902 XrdPoll: Poller 0 enabled /DC=ch/D.16468:7@lxplus115
190211 10:07:13 13902 /DC=ch/D.16468:7@lxplus115 XrdLink: Setting ref to 2+-1 post=0
190211 10:07:13 13902 XrootdsendResult: sent async ok to /DC=ch/D.16468:7@lxplus115
190211 10:07:13 13956 XrdSched: running main accept inq=0

**Comment by ffurano** [comment]
Hi Andy, I remember that our checks succeeded with your experimental fixes to XrdTransit. Have you finished committing them? Ok for you if I merge this PR ?

**Comment by abh3** [comment]
Hi Fabrizio,

Recall that we agreed that you would run a full test on the SLAC instance to verify that I didn’t break something else.

Andy

**Comment by ffurano** [comment]
Hi Andy,

 I can run functional tests, but not at scale. My suggestion was to
deploy it at SLAC and let it exposed to the DOMA TPC tests

f


Il 12/03/19 21:28, Andrew Hanushevsky ha scritto:

**Comment by abh3** [comment]
Hi Fabrizio,

Ah, that’s what I meant to say. A

**Comment by bbockelm** [comment]
@ffurano - please re-review / re-test the rebased branch.

With 32688283587637123e091ff66e458df6ade6ffbc, I now see the query returning successfully once the new checksum is calculated.

**Pull request merged**
