### PR TITLE
Reload certificate store once an hour.

### LINKED ISSUE #750: XrdHttp fails to refresh CRLs
Using xrootd 4.8.3, I observe the following after a few days:
```
139990299645696:error:80066405:lib(128):func(102):reason(1029):sslutils.c:1915:
139990299645696:error:80066411:lib(128):func(102):reason(1041):sslutils.c:2110:: CRL has expired [subject=/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management,issuer=/DC=ch/DC=cern/CN=CERN Grid Certification Authority]
139990299645696:error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed:s3_srvr.c:3327:
```
all over in our logs. 

Checking:
```
# ls -lart b4278411.r0 c2a48ab6.r0 5168735f.r0 4339b4bc.r0
-rw-r--r--. 1 root root  1535 19. Jun 12:47 c2a48ab6.r0
-rw-r--r--. 1 root root  1535 19. Jun 12:47 b4278411.r0
-rw-r--r--. 1 root root 33292 19. Jun 12:47 5168735f.r0
-rw-r--r--. 1 root root 33292 19. Jun 12:47 4339b4bc.r0
```
shows they are up-to-date (those are the CRLs for CERN-GridCA and CERN-Root-2, we run fetchcrl regulartly). 

Checking xrootd with `strace`, I find:
```
[pid 13040] futex(0x610f18, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10153] <... accept4 resumed> {sa_family=AF_INET6, sin6_port=htons(51392), inet_pton(AF_INET6, "::ffff:128.142.132.207", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28], SOCK_CLOEXEC) = 25
[pid 10153] setsockopt(25, SOL_SOCKET, SO_LINGER, {onoff=1, linger=3}, 8) = 0
[pid 10153] setsockopt(25, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
[pid 10153] setsockopt(25, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid 10153] futex(0x7ffc4e2a27b0, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  3022] <... futex resumed> )       = 0
[pid 10153] poll([{fd=25, events=POLLIN|POLLRDNORM}], 1, 30000 <unfinished ...>
[pid  3022] futex(0x610f18, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 13039] <... futex resumed> )       = 0
[pid 10153] <... poll resumed> )        = 1 ([{fd=25, revents=POLLIN|POLLRDNORM}])
[pid  3022] <... futex resumed> )       = 1
[pid 13039] futex(0x610f38, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 10153] recvfrom(25,  <unfinished ...>
[pid  3022] futex(0x610f38, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 13039] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 10153] <... recvfrom resumed> "\26\3\1\1\24\1\0\1\20\3\3[)'\305\261\351\17<\225C\232\311\27V\240\221q\t\377\26\275"..., 44, MSG_PEEK, NULL, NULL) = 44
[pid  3022] <... futex resumed> )       = 0
[pid 13039] futex(0x610f38, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 10153] poll([{fd=25, events=POLLIN|POLLRDNORM}], 1, 10000 <unfinished ...>
[pid  3022] futex(0x7ffc4e2a27b0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 13039] <... futex resumed> )       = 0
[pid 10153] <... poll resumed> )        = 1 ([{fd=25, revents=POLLIN|POLLRDNORM}])
[pid 13039] accept4(17,  <unfinished ...>
[pid 10153] recvfrom(25, "\26\3\1\1\24\1\0\1\20\3\3[)'\305\261", 16, MSG_PEEK, NULL, NULL) = 16
[pid 10153] epoll_ctl(7, EPOLL_CTL_ADD, 25, {0, {u32=738201208, u64=139990902247032}}) = 0
[pid 10153] setsockopt(25, SOL_SOCKET, SO_RCVTIMEO, "\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid 10153] setsockopt(25, SOL_SOCKET, SO_SNDTIMEO, "\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid 10153] read(25, "\26\3\1\1\24", 5) = 5
[pid 10153] read(25, "\1\0\1\20\3\3[)'\305\261\351\17<\225C\232\311\27V\240\221q\t\377\26\275\232G\260\300\276"..., 276) = 276
[pid 10153] write(25, "\26\3\3\0:\2\0\0006\3\3\24\275\332\341L+Tw:\2216\231\1\352~\213\37S\v\274."..., 2216) = 2216
[pid 10153] read(25, "\26\3\3\0378", 5) = 5
[pid 10153] read(25, "\v\0\0374\0\0371\0\3L0\202\3H0\202\2\261\240\3\2\1\2\2\1\0000\r\6\t*\206"..., 7992) = 7992
[pid 10153] stat("/etc/grid-security/certificates/c2a48ab6.r1", 0x7f523588a1f0) = -1 ENOENT (No such file or directory)
[pid 10153] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2309, ...}) = 0
[pid 10153] stat("/etc/grid-security/certificates/c2a48ab6.r1", 0x7f523588a1f0) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/e187c0c8.signing_policy", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/e187c0c8.namespaces", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/f27afd4e.signing_policy", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/f27afd4e.namespaces", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/4ad425d0.signing_policy", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/4ad425d0.namespaces", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/7768cc9b.signing_policy", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/7768cc9b.namespaces", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/5168735f.signing_policy", O_RDONLY) = 26
[pid 10153] ioctl(26, TCGETS, 0x7f5235889900) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] read(26, "# @(#)$Id: 4339b4bc.signing_poli"..., 8192) = 269
[pid 10153] read(26, "", 8192)          = 0
[pid 10153] ioctl(26, TCGETS, 0x7f5235889910) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] close(26)                   = 0
[pid 10153] open("/etc/grid-security/certificates/5168735f.namespaces", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10153] open("/etc/grid-security/certificates/c2a48ab6.signing_policy", O_RDONLY) = 26
[pid 10153] ioctl(26, TCGETS, 0x7f5235889900) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] read(26, "# @(#)$Id: b4278411.signing_poli"..., 8192) = 362
[pid 10153] read(26, "", 8192)          = 0
[pid 10153] ioctl(26, TCGETS, 0x7f5235889910) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] close(26)                   = 0
[pid 10153] open("/etc/grid-security/certificates/c2a48ab6.namespaces", O_RDONLY) = 26
[pid 10153] ioctl(26, TCGETS, 0x7f5235889900) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] read(26, "################################"..., 8192) = 774
[pid 10153] read(26, "", 8192)          = 0
[pid 10153] ioctl(26, TCGETS, 0x7f5235889910) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 10153] close(26)                   = 0
[pid 10153] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2309, ...}) = 0
[pid 10153] stat("/etc/grid-security/certificates/5168735f.r1", 0x7f523588a1f0) = -1 ENOENT (No such file or directory)
[pid 10153] write(25, "\25\3\3\0\2\2-", 7) = 7
[pid 10153] write(2, "139991062198016:error:80066405:l"..., 80) = 80
[pid 10153] write(2, "139991062198016:error:80066411:l"..., 261) = 261
[pid 10153] write(2, "139991062198016:error:14089086:S"..., 114) = 114
```

Any ideas what could be causing that? 

Restarting the xrootd service immediately gets rid of that issue.

### PR DESCRIPTION
**Pull request by bbockelm**
This triggers a reload of the cert store used for chain building and certificate verification (CRLs) once an hour.

Fixes #750

### CODE REVIEW

**Comment by abh3** [comment]
OK, here is the deal. Test this to the point you are happy it works. Then post the pull request against the stable release not R5 (it should be easily done). We are not implementing this in R5 as we have a cleaner solution and this will just muck things up going forward. If not, I will rework the R5 version  to back port to R4 (more difficult but not undoable). I don't want to spend the time doing that if you accept the deal (which I hope you do). OK?

**Comment by abh3** [comment]
Another nit, this has to work in vanilla RHEL6 which uses an older version of OpenSSL so some of the functions you use are not available there. I've been grappling with that as well.

**Comment by abh3** [comment]
BTW this is a serious problem as most RH6 sites are still running OpenSSL 1.0.1e-fips 11 Feb 2013 (not even version f!) which is way way back and doesn't have most of the features we would like. So, the original proposal of external reference counts is the only way this will work if we want to support refresh. I suppose we can deep six those sites and say we don't but you are still left with the old APIs that you need to deal with. This is not going to be as easy as one might think. I am looking at what I can do to accommodate all of this but someone has to decide whether or not we want to support refresh all the way back to 1.01e.

**Comment by abh3** [comment]
Ok, I final note. You really have to stop posting pull requests that only with RH7 or above. We are stuck supporting RH6 as the vast number of sites still run that. It just takes an enormous amount of time to realize that the pull request is not workable. So, please, test against RH6 before submitting a pull request. It will make all of our lives easier.

**Comment by abh3** [comment]
@bbockelm So, the consensus is to not support refresh for RH6, well not exactly but for any OpenSSL < version 1.02, so no need to turn into a pretzel. However, did you decide to take me up on the deal to include this (with appropriate if-defs) for 4.12 and perhaps 4.11? We really need to know as the release deadlines are fast approaching.

**Comment by bbockelm** [comment]
Hi @abh3 -

Sorry, just catching up.  I'm happy to put in the appropriate `#ifdef`'s for 4.12 while we put together a centralized, abstracted solution in V5.  I am absolutely slammed during the workweek but would hope to revise the PR over the weekend if that's an OK timeline for you.

Sorry about the RHEL6 build failures.  I don't have a RHEL6 host readily available (wouldn't hurt to give some tough love to sites -- I'd point out that, with RHEL's stated retirement schedule, EPEL6 will cease to exist in a measly 7 months!).  It would be immensely useful if perhaps @simonmichal could add a RHEL6 build to the Travis-CI tests.  That would allow you (and me!) to see immediately if there are problems 

Brian

**Comment by abh3** [comment]
Well, the good news is that it's done for R5 and integrated into the overall TLS framework. Lot's of https-openSSL code just vaporized. We could even vaporize a lot more code if we use the underlying TLS I/O implementation instead of dealing directly with SSL connections via bio's.. That's left for phase 2. Anyway I am testing it now and it all looks good. What I am missing is a simple but effective https application that needs voms authentication. Do you have one?

**Comment by simonmichal** [comment]
Hi guys, is there a consensus about this one? My impression was that we will have a PR for stable-4.12.x only, as in R5 we will have a more complete solution, is this correct?

**Comment by xrootd-dev** [comment]
Yes, that was the correct impression. Right now that 4.12.x pr is waiting 
on Brian who, I am sure, is diligently workng on as he already had the 
first take on it.

**Comment by bbockelm** [comment]
Closing this now prior to reopening the V4 version.

**Pull request closed without merging**
