### PR TITLE
Overhaul logging approach for TPC

### LINKED ISSUE #1049: Netlogger Format to log XRootD Transfers/Accesses
It would be beneficial to have xrootd logging improved and maybe use the format like gridftp [1]. In this case sites could filter out transfers from/to or was it transfer or partial read and also what is the return code, start time/end time, etc.. 

@bbockelm fyi

[1]
http://netlogger.lbl.gov/doc 
```
DATE=20190825171337.391455 HOST=transfer-2.ultralight.org PROG=globus-gridftp-server NL.EVNT=FTP_INFO START=20190825171336.718219 USER=cmsuser FILE=/mnt/hadoop/store/temp/user/lprado.ebec82b11611038a27d0e84af28c86023041fded/TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8/tthbb_sl_94X_v1/190822_141133/0001/ntuples_JESAbsoluteScaleup_Tree_1318.root BUFFER=235392 BLOCK=1048576 NBYTES=15171584 VOLUME=/ STREAMS=1 STRIPES=1 DEST=[131.225.204.196] TYPE=RETR CODE=226 TASKID=none retrans=4
DATE=20190825171400.100718 HOST=transfer-2.ultralight.org PROG=globus-gridftp-server NL.EVNT=FTP_INFO START=20190825171241.934773 USER=phedex FILE=/mnt/hadoop/store/mc/RunIIFall17MiniAODv2/ST_FCNC-TH_Tleptonic_HToWWZZtautau_Ctphi_CP5_13TeV-mcatnlo-madspin-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/270000/3E1901CA-41B5-E911-BA06-0090FAA572E0.root BUFFER=332800 BLOCK=1048576 NBYTES=3656287425 VOLUME=/ STREAMS=1 STRIPES=1 DEST=[131.225.207.226] TYPE=STOR CODE=226 TASKID=none
DATE=20190825171428.979333 HOST=transfer-2.ultralight.org PROG=globus-gridftp-server NL.EVNT=FTP_INFO START=20190825171354.811325 USER=cmsuser FILE=/mnt/hadoop/store/temp/user/dwinterb.7b5457f8effb276e55b427b22fcd49d760da706b/Aug22_MC_102X_2018/GluGluToMaxmixHToTauTauPlusTwoJets_M125_13TeV_amcatnloFXFX_pythia8/crab_GluGluToMaxmixHToTauTauPlusTwoJets_M125_amcatnloFXFX/190823_084946/0000/EventTree_186.root BUFFER=234912 BLOCK=1048576 NBYTES=655815949 VOLUME=/ STREAMS=1 STRIPES=1 DEST=[2A0C:5BC0:C8:2:B226:28FF:FE1E:C8F0] TYPE=RETR CODE=226 TASKID=none retrans=29
```

### PR DESCRIPTION
**Pull request by bbockelm**
Try to consistently give a machine-readable format that is friendly to tools like `grep`.

Example messages (split over lines for human readability):

```
200315 14:21:06 1875839 TPC_PullRequest: event=PULL_START, \
    local=/home/bbockelm/hello_world_copy.txt, \
    remote=http://example.com:8000/hello_world_copy.txt, \
    user=(anonymous); Starting a push request
200315 14:21:06 1875839 TPC_PullRequest: event=OPEN_FAIL, \
    local=/home/bbockelm/hello_world_copy.txt, \
    remote=http://example.com:8000/hello_world_copy.txt, \
    user=(anonymous), streams=2, status=401; \
    Unable to create /hello_world_copy.txt; permission denied
```

Fixes #1049

### CODE REVIEW

**Comment by bbockelm** [comment]
@ffurano - I think this is ready to go.

**Comment by ffurano** [comment]
Hi Brian,  have the configuration file changes been documented?
Could you please resolve the conflict?

**Comment by bbockelm** [comment]
@ffurano - yup, some of these PRs mutually conflicted.  Working on this now...

**Comment by bbockelm** [comment]
@ffurano - conflicts resolved and re-tested.

For documentation, this PR introduces the following configuration parameters:
```
tpc.trace [all | error | warning | info | debug | none]+
```
The default is equivalent to `tpc.trace info warning error`.  The options are not additive (that is, `info` does not imply `error`) except for `all`; `all` implies all defined logging levels.

**Pull request merged**
