### PR TITLE
Fill the XrdSecEntity struct according to the last discussions,

### PR DESCRIPTION
**Pull request by ffurano**
in particular about the short name

### CODE REVIEW

**Comment by bbockelm** [comment]
This appears to fix two out of three memory leaks also fixed by #493.  To make backporting easier, can you separate the bugfixes and new features to separate commits?  Or maybe just make sure #493 is merged first?

Thanks!

**Comment by xrootd-dev** [comment]
Just to make sure I don’t make a mess. I first pull 493 and then afterwards 495 and no conflicts will arise, right?

Andy

**Comment by bbockelm** [comment]
I suspect 495 won't be mergeable after 493 goes in.

But Fabrizio can then easily fix the merge - and you have an easier time backporting!

Brian

**Comment by gganis** [comment]
Hi Fabrizio,

I am not 100% sure, but for XrdSecEntity.name in the case no username was specified, I thought we said to take the last 8 digits of the first '/CN=', without spaces, i.e., from '.../CN=Fabrizio Furano/...' we should have got 'ioFurano' . 
If that is the case, then I am not sure the code does that: the buffer is 64 in length and the space is not removed.
Do I remember wrongly?

Gerri

**Comment by abh3** [comment]
Hi All,

Gerri remembers correctly. The 8 character name is the one that gets put into the loginid for "kXR_login”. The entity structure name is, in fact, the full distinguished name. Unless someone tells me otherwise in the next couple of hours, I will merge in 495 (which should include Brian’s fix) and then Fabrizion will have to generate a new pull request with the login-name fix.

Andy

**Comment by xrootd-dev** [comment]
Ciao Gerri,

 indeed, I forgot to shorten the name. Good that you don't share the other doubts I had.
 Thank you for the review, I hope I'll be able to do this today-ish

f

**Comment by xrootd-dev** [comment]
Hi again,

 I am on this small thing, and re-re-re-read the notes. They
were mentioning only the link name for this 8-chars thing. Not
SecEntity.name

 In fact I believe it would make no sense to mangle the username, would it ?

f

**Comment by abh3** [comment]
Hi Fabrizio,

Obviously you figured it out beacause you had a pull request for this. 
Indeed, we were only talking about the link name not the qualified name.

Andy

**Comment by ffurano** [comment]
Hi Andy,

 yes, a quick call to Gerri and we agreed on what you say. I hope it's good now,
in any case please let me know.

Fabrizio

**Pull request merged**
