### PR TITLE
[XrdHttp][XrdVoms] Pass parameters specified in the http.secxtractor …

### PR DESCRIPTION
**Pull request by esindril**
…down the chain

Conflicts:
	src/XrdHttp/XrdHttpProtocol.cc

### CODE REVIEW

**Comment by esindril** [comment]
This allows passing the secxtractor params down the chain. Otherwise enabling debug for the secxtractor library is impossible. Could this also please be backported to the 4.12 branch?

**Comment by abh3** [comment]
Elvin, clearly your editor is not to task here. It looks like everything has changed because all blank lines have been replaced by, well ,blank lines! It's impossible to review this pull request. Could you re-post this pull request with that issue solved (you can easily see it on github).

**Comment by esindril** [comment]
I was hoping to get rid of those annoying whitespaces and that's why I left them in. Ok, I will make another pull request only for whitespace cleanup. :)

**Comment by esindril** [comment]
This is good now from my side.

**Pull request merged**
