### PR TITLE
Fix digest names returned to clients.

### PR DESCRIPTION
**Pull request by bbockelm**
Digest name issues reported by @olifre.

@simonmichal - Should be included in 4.10, if possible.

### CODE REVIEW

**Comment by simonmichal** [comment]
@bbockelm : sure, however Fabritzio is on DPM workshop so we will have to wait until Monday with the next RC

**Comment by olifre** [comment]
@simonmichal @bbockelm Thanks! 
Once it is in an RC, I can also roll it out to UNI-BONN endpoint and see how it fares in interoperability with dCache. I'll be on holidays next week, so no promises if I'll get to it already next week (but latest in two weeks from now).

**Comment by olifre** [comment]
I can confirm with 4.10.0-rc3, which contains this PR, the observed issues are fixed (which showed up mainly in XRootD talking with dCache). 
I'm still unsure whether #1002 would not have been the "better" (or rather, cleaner) implementation - @bbockelm , what's your take on this?

**Comment by bbockelm** [comment]
@olifre - #1002 is probably cleaner code, but this gets us the same place.  The bigger picture is the algorithm selection code needs to be rewritten anyway: we currently take the first supported algorithm on the list while we really should respect the client-provided priorities.

**Comment by olifre** [comment]
> he bigger picture is the algorithm selection code needs to be rewritten anyway: we currently take the first supported algorithm on the list while we really should respect the client-provided priorities.

Ok, I see - thanks for the explanation!

**Pull request merged**
