### PR TITLE
[XrdClTests] Stop some intermittent failures of XrdClTests/SocketTest

### PR DESCRIPTION
**Pull request by smithdh**
Hi @amadio I hope I found the reason for the intermittent failures in XrdClTests (SocketTest, often in almalinux9 apparently) and I've made a patch for it.

### CODE REVIEW

**Comment by smithdh** [comment]
(Well, lets see)

**Comment by amadio** [comment]
Yes, this test is failing quite often on Alma and Alpine Linux. Could you please explain the change contained in the patch in the commit message? Thank you!

**Comment by smithdh** [comment]
Hi. I've updated the commit message.

**Comment by amadio** [comment]
Thank you!

**Pull request merged**
