### PR TITLE
Absent CRL is not an error (issue #465)

### PR DESCRIPTION
**Pull request by ellert**
This is a proposed fix for issue #465.

### CODE REVIEW

**Comment by gganis** [comment]
I see the problem, but I believe the fix should be in the way the null return is interpreted.
I am preparing a patch. Let you know when I am done.

**Comment by gganis** [comment]
I have just uploaded a patch for #465 fixing the interpretation of the return code.
So I am closing this PR without merging it.

**Comment by ellert** [comment]
CRLCheck = 1 is supposed to implement the standard behaviour, i.e. "use if present". This means that a missing CRL should nor be considers an error. But it also means that a present but expired CRL should trigger an error. The code still treats a missing and an expired CRL the same. Now it accept both instead of rejecting both as it did before, but it should accept a missing CRL while rejecting an expired one.

**Comment by gganis** [comment]
Expired CRL contain valid information though not updated. As documented (http://xrootd.org/doc/dev45/sec_config.htm#_Toc464225463) CRLCheck=1 is expected to trigger an error is the loaded CRL is invalid for other reasons (for example if the signature verification fails), 
but accepts expired but otherwise valid CRLs, as CRLCheck=2 does.

**Comment by gganis** [comment]
Forgot to mention the a patch uploaded to day to the HEAD of stable-4.6.x and master makes sure that the documented behaviour is honoured.

**Pull request closed without merging**
