### PR TITLE
[XrdCl] Check for closed connection between handling of read and write events

### PR DESCRIPTION
**Pull request by smithdh**
This change is to fix issue #1934.

### CODE REVIEW

**Comment by simonmichal** [comment]
@smithdh : thanks a lot for the PR. OK I see this is handling the case when w have Bothe read and write events, and on the read event there's an error and the socket gets disconnected, in this case we are not suppose to handle the write event, is this correct? 
Is this only a problem in case the stream gets reconnected and assigned to a different event loop, or is this a problem in general because the stream got closed and the write event is invalid?

**Comment by smithdh** [comment]
Hi @simonmichal I'm only aware of a problem when the AsyncSocket is re-opened and reassigned to another poller.

I just re-pushed a change to specify relaxed memory order on the std::atomic introduced by this patch; it took a while to convince myself this was ok (not that this makes any difference in generated code, in this case and on intel). I see we generally use relaxed order with std::atomics, and a comment in the XrdSys XrdSysRAtomic utility class contains a a suggestion to use a mutex to some cases, where a stronger guarantee is needed, explicit.

**Comment by abh3** [comment]
Hi David,

I would suggest using XrdSysRAtomic.hh whenever a relaxed atomic is 
wanted. This is the only way to gaurantee that everyone uses that mutex in 
relaxed mode. People forget as we have seen.

Andy

**Comment by smithdh** [comment]
Hi. Thanks, I've replaced the std::atomic that this patch was introducing with RAtomic.

**Comment by smithdh** [comment]
Hi @simonmichal I've realised that there are some paths where the read event action (e.g. OnReadTimeout) can cause the AsyncSocketHandler to be not only closed but destroyed too. So this patch does nothing to help in those cases (and adds at least one access to invalid memory); so I'd propose to abandon/close this PR. I will look for another solution.

**Pull request closed without merging**
