### PR TITLE
Xrdpfc new cmd line option. print in json format

### PR DESCRIPTION
**Pull request by juztas**
This will be much easier for other clients (tools reading cinfo file). This is mainly an interest for cache work in CMS with Rucio.

### CODE REVIEW

**Comment by juztas** [comment]
Output example:
```
FILE: /root/b//5.cinfo
{ "file": "\/root\/b\/\/5.cinfo", "version": 4, "created": "Wed Sep  1 05:46:39 2021", "cksum": "none", "no-cksum-time": "Wed Sep  1 05:46:40 2021", "file_size": 2984562, "buffer_size": 512, "n_blocks": 5830, "state_complete": "complete", "state_percentage": 100.000000, "block_array": [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ........], "n_acc_total": 2, "accesses": [ { "record": 1, "attach": "210901:054639", "detach": "210901:055534", "duration": "0:08:55", "n_ios": 1, "n_mrg": 0, "B_hit[kB]": 1363092, "B_miss[kB]": 37541, "B_bypass[kB]": 0 }, { "record": 2, "attach": "210904:105959", "detach": "210904:125346", "duration": "1:53:47", "n_ios": 1, "n_mrg": 0, "B_hit[kB]": 1500826, "B_miss[kB]": 0, "B_bypass[kB]": 0 } ] }
```

**Comment by juztas** [comment]
I just tried on a fresh machine. Correct, it does not complain about `json-c`, likewise it is for UUID. The only thing it writes to error:
```
-- Checking for module 'json-c'
--   No package 'json-c' found
-- Checking for module 'uuid'
--   No package 'uuid' found
```
After those 2 devel packages are installed, the next issue seems it also need a libuuid-devel package (seems needed for Macaroons) Is there a reason? I would suggest making something like this:

```
diff --git a/cmake/XRootDFindLibs.cmake b/cmake/XRootDFindLibs.cmake
index 532c8ce..39654ad 100644
--- a/cmake/XRootDFindLibs.cmake
+++ b/cmake/XRootDFindLibs.cmake
@@ -95,10 +95,12 @@ endif()

 find_package( Macaroons )
 include (FindPkgConfig)
-pkg_check_modules(JSON json-c)
+pkg_check_modules(JSON json-c REQUIRED)
 pkg_check_modules(UUID uuid)
+pkg_check_modules(LIBUUID libuuid)

-if( MACAROONS_FOUND AND JSON_FOUND AND UUID_FOUND )
+
+if( MACAROONS_FOUND AND JSON_FOUND AND UUID_FOUND AND LIBUUID_FOUND )
   set( BUILD_MACAROONS TRUE )
 else()
   set( BUILD_MACAROONS FALSE )
```
It might not need anymore this JSON_FOUND... as it becomes REQUIRED

**Comment by abh3** [comment]
Yes, indeeed that one. I grabbed and renamed it to correspond to out 
naming conventions. I can push  it to master ahead of time and you can 
simply start usinhg that. Yes?

**Comment by osschar** [comment]
ok, i can then modify what we have in xrdpfc_print to use it.

**Comment by abh3** [comment]
It has been done. See XrdOuc/XrdOucJson.hh

**Comment by osschar** [comment]
Thank you! And I committed the change :)

@juztas, are you sure you want to keep:
1. [kB] in B_hit/miss/bypass ... they are not in file_size, and buffer_size (which are also << 10);
2. the initial line with FILE: ....

One could make -j option take an int argument, to specify pretty-print alignment ... I just use minimal dump (no whitespace, no new lines) now.

```
{"accesses":[{"B_bypass[kB]":0,"B_hit[kB]":0,"B_miss[kB]":0,"attach":"210928:162058","detach":"210928:162059","duration":"0:00:01","n_ios":1,"n_mrg":0,"record":1},{"B_bypass[kB]":0,"B_hit[kB]":0,"B_miss[kB]":0,"attach":"210928:164632","detach":"210928:164634","duration":"0:00:02","n_ios":1,"n_mrg":0,"record":2},{"B_bypass[kB]":0,"B_hit[kB]":0,"B_miss[kB]":313344,"attach":"210929:080250","detach":"210929:080304","duration":"0:00:14","n_ios":1,"n_mrg":0,"record":3},{"B_bypass[kB]":0,"B_hit[kB]":313344,"B_miss[kB]":4105190,"attach":"210929:080818","detach":"210929:081144","duration":"0:03:26","n_ios":1,"n_mrg":0,"record":4}],"buffer_size":1024,"cksum":"none","created":"Tue Sep 28 16:20:58 2021","file":"../data/store/user/matevz/xmxxx-2018-02.root.cinfo","file_size":4418534,"n_acc_total":4,"n_blocks":4315,"no-cksum-time":"Wed Sep 29 08:02:52 2021","state_complete":"complete","state_percentage":100.0,"version":4}
```

There is some work one could do to cleanup directory traversal printouts when a directory is given as an argument, in particular, to not print "not a cinfo file" and stat a file if it is directory before trying to read it as cinfo file.

**Comment by juztas** [comment]
No preference on name ;)

**Comment by osschar** [comment]
Now you're making it hard for me :) If you want to use this for further reporting, I suspect that downward-rounding when using kB as unit (esp. for file_size) could give you some trouble. I think using plain bytes would be better.

One could introduce another option ```-unit [kM]``` but as json is meant for machine consumption it would probably just make things more error prone.

**Comment by juztas** [comment]
Lets use plain bytes then ;). Thanks!

**Comment by osschar** [comment]
Alrighty, plain-bytes JSON is in master. I couldn't stop myself and implemented ```-unit [B|kB|MB]``` for the standard printout, it seems I miss good old good fortran, sniffle :)

**Pull request merged**
