### PR TITLE
[XrdHttp] A bad request error is returned in the case a client provides too many range requests

### PR DESCRIPTION
**Pull request by ccaffy**
Fixes issue https://github.com/xrootd/xrootd/issues/2003

### CODE REVIEW

**Comment by ccaffy** [comment]
If a client asks for more than the maximum amount of vector reads the server can handle, they will get a 400 error "Bad Request" like the following:

```
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Connection: Close
header: Server: XrootD/v5.2.0-99-osghotfix...687
header: Content-Length: 74
Too many range requests provided. Maximum range requests supported is 1024
```

**Review by abh3 — COMMENTED** [review]
I agree that this addresses the issue of a read vector being too long in the first place. However, I think you decided hat there is more work to do on this other than complaining that the number of element in the read vector is too long. So, I don't see anything wrong but I would guess you wan to expand on this pull request to do a more comprehensive patch, right? So, I won't merge this unless you tell me this is what you really want in.

**Comment by ccaffy** [comment]
Hi @abh3 ,

You can merge this one. It solves this issue and this issue can therefore be closed. The other problem I am working on related to range-request is in this issue: https://github.com/xrootd/xrootd/issues/1976

Cheers,
Cedric

**Comment by abh3** [comment]
Thanks, I merged it but I still don't know which related ticket should be 
closed. Can you give that ticket number?

**Comment by ccaffy** [comment]
> Thanks, I merged it but I still don't know which related ticket should be closed. Can you give that ticket number?
> […](#)
> On Wed, 7 Jun 2023, ccaffy wrote: Hi @abh3 , You can merge this one. It solves this issue and this issue can therefore be closed. The other problem I am working on related to range-request is in this issue: #1976 Cheers, Cedric -- Reply to this email directly or view it on GitHub: [#2022 (comment)](https://github.com/xrootd/xrootd/pull/2022#issuecomment-1580063022) You are receiving this because you were mentioned. Message ID: ***@***.***>

Closing the ticket, I've put its number in the first comment of this pull request: https://github.com/xrootd/xrootd/issues/2003

**Pull request merged**
