### PR TITLE
SecProtocolgsi: Local copy of url supplied proxy location

### PR DESCRIPTION
**Pull request by smithdh**
This is a draft patch for #2292

### CODE REVIEW

**Comment by smithdh** [comment]
The issue is thought to be around the extraction and storage of the value of a "xrd.gsiusrpxy" url-option (or one of the other similar url parameters). The extraction is done by an XrdSecProtocolgsi object. Values are extracted from the url during the method XrdSecProtocolgsi::getCredentials() and used during XrdSecProtocolgsi::ClientDoInit(). The url value is stored in the variable UsrProxy (overwriting the existing value). UsrProxy is static (static class member), and may be initialised during XrdSecProtocolgsi::Init (a static class method): so updating it during a non-static method leads to potential concurrent update of the member (a String) by different class instances, and also means one request can affect other requests in an unexpected way.

The PR changes the approach to store the url value in a non-static member, and then evaluate the actual value to use during ClientDoInit() based on the static UsrProxy value and the actual url-option value.

**Comment by smithdh** [comment]
Hi. I'll update with more information about the testing of this PR: our FTS team did try to test this patch in their service, but encountered some problems. For the time being there's been no chance to understand what exactly happened (and there won't be chance to discuss with the person who ran the test for a little while). So for now I don't think I'll move this PR out of draft.

The patch itself seems alright to me, and I've done some tests myself that show a problem and the expected fix. However as it does change some observed behaviour it's possible a client could have depended on the previous behaviour, so perhaps caution is needed.

**Comment by amadio** [comment]
The problem in FTS was due to the changes in `devel` which break APIs as far as I know. They should apply this patch on top of 5.7.0 and try again.

**Review by abh3 — APPROVED** [review]
I am not completely familiar with the original issue here. From my petspective. It would appear that the attempt here is to use the proxy value in the url's cgi to override the one that came from elsewhere. If so, that is what has been implemented here. What I don't understand, based on various comments, why/how this problem was introduced in the first place. So, I cannot comment on whether this is a good fix, though according to @smithdh itr appears to work.

**Comment by smithdh** [comment]
Hi. I'll update this ticket with the current status & summary. These were already discussed within the team but I add an update here for clarity. There were two connected aspects to the problem that this PR should fix:

(i) a problem that was causing #2292, which is an issue that may show when there are concurrent connections using gsi, and where each connection has a different proxy location specified by &xrd.gsiusrpxy.

(ii) The default location to look for gsi proxy is changed after a processing a connection which specified a particular location with a &xrd.gsiusrpxy. (Subsequent connections that don't specify &xrd.gsiusrpxy look in the last specified location). No concurrency is required to show this behaviour.

This patch fixes/changes both (i) & (ii). But the change for issue (ii) had caused a first test of this patch by FTS to fail, due to the changed in behaviour, within XrdCl/XrdClThirdPartyCopyJob.cc. A second commit was added to this PR to fix that.

I'll move this PR out of draft status now. But I believe the preference is to keep this unmerged for now.

**Comment by amadio** [comment]
@smithdh Could you please rebase this locally and push, since it has conflicts previnting automatic rebase? Thank you!

**Pull request merged**
