### PR TITLE
XrdTlsContext: Recreate session cache in the Clone() method

### PR DESCRIPTION
**Pull request by ccaffy**
This fixes the issue #1874

### CODE REVIEW

**Comment by ccaffy** [comment]
Hi @abh3 ,

Here is the fix. I tested it both with HTTP and xroots and it works fine.

Cheers,
Cedric

**Review by abh3 — APPROVED** [review]
Sorry for the late review but we were off the day before this was posted -- 2.5 weeks of bliss :-) Anyway, it looks good so please merge it and thanks for doing the fix!

**Comment by abh3** [comment]
OK, I decided to merge it myself as it was a no brainer!

**Comment by ccaffy** [comment]
Thanks @abh3 and happy new year!

**Pull request merged**
