### PR TITLE
Refactor user name extraction from certificate CN

### PR DESCRIPTION
**Pull request by mpatrascoiu**
When using `sec.potocol gsi` with `-authzfun:libXrdSecgsiAUTHZVO.so` and `-authzfunparms with empty vo2usr` , the behavior is to extract the user name from the certificate's /CN field. 

This commit refactors the name extraction to only the first CN encountered.
A text limitation to N characters is respected, where N = length of entity.vorg.

Previously, it would grab all the text after the CN field, stopping either at the end or when N characters were met.

### CODE REVIEW

**Comment by bbockelm** [comment]
I'm not sure you want the first one.  Maybe the last one?  For example, here's my CERN DN:

`/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=bbockelm/CN=659869/CN=Brian Paul Bockelman`

With this patch, the username would be `659869`, no?

**Comment by mpatrascoiu** [comment]
Hello Brian,

With the change, the username would be bbockelm.

A complete solution would be to add another argument to the `-authzfunparms` to decide between the first CN, last CN or all of them but I'm not sure that would be something which is needed.

**Comment by xrootd-dev** [comment]
Another concern is that some sites may expect the old behavior and changing this would break things.

**Comment by ffurano** [comment]
Hi,
 for the records, I have no preference for the solutions, they are both equally bad to me (not that I see a good one elsewhere)

**Pull request closed without merging**
