### PR TITLE
[XrdTpcTPC] PMarkManager - corrected a segfault that may happen in the creation of the first packet marking handle

### PR DESCRIPTION
**Pull request by ccaffy**
Fixes the issue https://github.com/xrootd/xrootd/issues/2161

### CODE REVIEW

**Review by abh3 — COMMENTED** [review]
Seems like auto does not deduce reference types in templates. See,
https://stackoverflow.com/questions/56429977/auto-return-type-not-deducing-reference

The suggested fix is to use decltype as the post points out. Alternatively, explicitly specify the correct type. What is your opinion?

**Comment by amadio** [comment]
Looks good to me, feel free to merge, or I will do it tomorrow. Thanks!

**Comment by ccaffy** [comment]
> Seems like auto does not deduce reference types in templates. See, https://stackoverflow.com/questions/56429977/auto-return-type-not-deducing-reference
> 
> The suggested fix is to use decltype as the post points out. Alternatively, explicitly specify the correct type. What is your opinion?

Yes, will use the correct type instead of auto ;) Will test a home-made compiled version of XRootD against EOS before pushing this fix for the merge ;)

**Comment by ccaffy** [comment]
All good, I've tried this fix on EOS and everything work fine now.
Thanks for the merge !

Cheers,
Cedric

**Pull request merged**
